### ISSUE TITLE
hello sir, i m new developer of Angularjs  plz give me the solutation of my problem.

### ISSUE THREAD

**Issue by Shameemkhands8519** [PacktPublishing/Practical-Internet-of-Things-with-JavaScript#2]
sir, when i inject my service.js dependency in my controller but still error occured  unknow provider

angular.js:13642 Error: [$injector:unpr] http://errors.angularjs.org/1.5.6/$injector/unpr?p0=OtpServiceProvider%20%3C-%20OtpService%20%3C-%20otpSendController
    at angular.js:38
    at angular.js:4501
    at Object.d [as get] (angular.js:4654)
    at angular.js:4506
    at d (angular.js:4654)
    at e (angular.js:4678)
    at Object.invoke (angular.js:4700)
    at P.instance (angular.js:10177)
    at n (angular.js:9096)
    at g (angular.js:8459)

**Comment by arvindr21** [comment]
Looks like OTP service provider is not included in the index.html file or there may be a spelling mistake somewhere.

Also, please ask questions related to this book only here.

**Comment by Shameemkhands8519** [comment]
thankx sir and sorry sir
